# Keep in sync with https://github.com/edgarrmondragon/.github/blob/main/.github/FUNDING.yml
github: [edgarrmondragon]
patreon: edgarrmondragon
ko_fi: edgarrmondragon
polar: edgarrmondragon
thanks_dev: u/gh/edgarrmondragon

tidelift: pypi/citric
