tasks:
  - init: |
      docker-compose pull
      docker-compose build
      pyenv install --skip-existing
  - command: |
      docker-compose --profile=web up

image: gitpod/workspace-python-3.11:latest

ports:
  - port: 8001
    onOpen: open-browser
    visibility: public
  - port: 9001
    onOpen: open-browser

vscode:
  extensions:
    - ms-python.python
    - ms-toolsai.jupyter

github:
  prebuilds:
    master: true
    pullRequests: true
