tasks:
  - init: |
      docker compose pull
      docker compose build
  - env:
      LS_USER: "citric_gitpod"
      LS_PASSWORD: "notverysecret"
      PUBLIC_URL: https://8001-edgarrmondragon-citric-${GITPOD_WORKSPACE_ID}.gitpod.io
    command: |
      docker compose --profile=web up

ports:
  - port: 8001
    onOpen: open-browser
    visibility: public
  - port: 9001
    onOpen: open-browser

vscode:
  extensions:
    - ms-python.python
    - ms-toolsai.jupyter

github:
  prebuilds:
    master: true
    pullRequests: true
