tasks:
  - init: |
      docker-compose pull
      docker-compose build
  - command: |
      docker-compose -f docker-compose.yml -f docker-compose.jupyter.yml up

ports:
  - port: 8001
    onOpen: open-browser
    visibility: public
  - port: 9001
    onOpen: open-browser
  - port: 8888
    onOpen: open-browser

vscode:
  extensions:
    - ms-python.python
    - ms-toolsai.jupyter

github:
  prebuilds:
    master: true
    pullRequests: true
