version: 2

build:
  os: ubuntu-24.04
  tools:
    python: "3.12"
  jobs:
    post_checkout:
      - git fetch --unshallow || true

sphinx:
   configuration: docs/conf.py
   fail_on_warning: true

python:
  install:
    - method: pip
      path: .
    - requirements: docs/requirements.txt
