version: 2

build:
  os: ubuntu-24.04
  tools:
    python: "3.14" # NOTE: Keep this in sync with noxfile.py
  jobs:
    post_checkout:
      - git fetch --unshallow || true
    pre_create_environment:
      - asdf plugin add uv
      - asdf install uv latest
      - asdf global uv latest
    create_environment:
      - uv venv "${READTHEDOCS_VIRTUALENV_PATH}"
    install:
      - UV_PROJECT_ENVIRONMENT="${READTHEDOCS_VIRTUALENV_PATH}" uv pip install -r requirements/docs.requirements.txt
      - UV_PROJECT_ENVIRONMENT="${READTHEDOCS_VIRTUALENV_PATH}" uv pip install .

sphinx:
  builder: html
  configuration: docs/conf.py
  fail_on_warning: true
