version: 2

build:
  os: ubuntu-24.04
  tools:
    python: "3.13"
  jobs:
    post_checkout:
      - git fetch --unshallow || true
    create_environment:
      - asdf plugin add uv
      - asdf install uv latest
      - asdf global uv latest
    install:
      - uv sync --frozen --no-dev --group docs
    build:
      html:
        - uv run sphinx-build -T -b html docs $READTHEDOCS_OUTPUT/html

sphinx:
   configuration: docs/conf.py
   fail_on_warning: true
