version: '3'

services:
  db:
    image: postgres:14
    environment:
      POSTGRES_USER: limesurvey
      POSTGRES_DB: limesurvey
      POSTGRES_PASSWORD: secret
    ports:
      - "5432:5432"
    volumes:
      - "limedb:/var/lib/postgresql/data"

volumes:
  limedb:
