name: Install tools
description: Install tools for Python projects

inputs:
  nox-version:
    description: "The version of Nox to install"
    required: true
  uv-version:
    description: "The version of uv to install"
    required: true

runs:
  using: "composite"
  steps:
  - name: Install uv
    # TODO: Update this manually until
    # https://github.com/davidism/gha-update/issues/6
    uses: astral-sh/setup-uv@180f8b44399608a850e1db031fa65c77746566d3 # v5.0.1
    with:
      version: ${{ inputs.uv-version }}

  - name: Install Nox
    shell: bash
    run: |
      uv tool install --with nox==${{ inputs.nox-version }} nox
      nox --version
