name: Install tools
description: Install tools for Python projects

inputs:
  constraints:
    default: ".github/workflows/constraints.txt"
    description: "Path to pip constraints file"
    required: true
  os:
    default: "ubuntu-latest"
    description: "Operating system"
    required: true

runs:
  using: "composite"
  steps:
  - name: Upgrade pip
    shell: bash
    env:
      PIP_CONSTRAINT: ${{ inputs.constraints }}
    run: |
      python -m pip install pip
      pip --version

  - name: Upgrade pip in virtual environments
    shell: python
    run: |
      import os
      import pip

      with open(os.environ["GITHUB_ENV"], mode="a") as io:
          print(f"VIRTUALENV_PIP={pip.__version__}", file=io)

  - name: Install Hatch
    shell: bash
    env:
      PIP_CONSTRAINT: ${{ inputs.constraints }}
    run: |
      pipx install hatch --verbose
      hatch --version

  - name: Install Nox
    shell: bash
    env:
      PIP_CONSTRAINT: ${{ inputs.constraints }}
    run: |
      pipx install nox
      nox --version
