name: Install tools
description: Install tools for Python projects

inputs:
  nox-version:
    description: "The version of Nox to install"
    required: true
  uv-version:
    description: "The version of uv to install"
    required: true

runs:
  using: "composite"
  steps:
  - name: Install uv
    # TODO: Update this manually until
    # https://github.com/davidism/gha-update/issues/6
    uses: astral-sh/setup-uv@f0ec1fc3b38f5e7cd731bb6ce540c5af426746bb # v6.1.0
    with:
      version: ${{ inputs.uv-version }}

  - name: Install Nox  # zizmor: ignore[template-injection]
    shell: bash
    run: |
      uv tool install --with nox==${{ inputs.nox-version }} nox
      nox --version
