name: Install tools
description: Install tools for Python projects

inputs:
  constraints:
    default: "${{ github.workspace }}/.github/workflows/constraints.txt"
    description: "Path to pip constraints file"
    required: true
  os:
    default: "ubuntu-latest"
    description: "Operating system"
    required: true

runs:
  using: "composite"
  steps:
  - name: Install uv
    uses: astral-sh/setup-uv@v3
    with:
      version: "0.5.x"

  - name: Install Nox
    shell: bash
    run: |
      uv tool install nox
      nox --version
