name: Build

on:
  push:
  workflow_dispatch:
    inputs:
      publish:
        description: "Publish to PyPI?"
        required: true
        default: false
        type: boolean
      tag:
        description: "Tag to use for release"
        required: true

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

permissions: {}

jobs:
  build:
    name: Build wheel and sdist
    runs-on: ubuntu-24.04
    outputs:
      version: ${{ steps.baipp.outputs.package_version }}
    steps:
    - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      with:
        ref: ${{ github.event.inputs.tag || github.ref }}
        persist-credentials: false
    - uses: hynek/build-and-inspect-python-package@fe0a0fb1925ca263d076ca4f2c13e93a6e92a33e # v2.17.0
      id: baipp

  publish:
    name: Publish to PyPI
    if: startsWith(github.ref, 'refs/tags/') || github.event.inputs.publish == 'true'
    runs-on: ubuntu-24.04
    needs: [build]
    environment:
      name: pypi
      url: https://pypi.org/project/citric/${{ needs.build.outputs.version }}
    permissions:
      id-token: write # IMPORTANT: mandatory for trusted publishing

    steps:
    - uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c # v8.0.1
      with:
        name: Packages
        path: dist
    - uses: pypa/gh-action-pypi-publish@cef221092ed1bacb1cc03d23a2d87d1d172e277b # v1.14.0

  sign:
    name: Sign the distribution package
    if: startsWith(github.ref, 'refs/tags/') || github.event_name == 'workflow_dispatch'
    runs-on: ubuntu-24.04
    needs: [build]
    permissions:
      contents: write     # IMPORTANT: mandatory for making GitHub Releases
      id-token: write     # IMPORTANT: mandatory for attestations
      attestations: write # IMPORTANT: mandatory for attestations

    steps:
      - uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c # v8.0.1
        with:
          name: Packages
          path: dist
      - uses: actions/attest@59d89421af93a897026c735860bf21b6eb4f7b26 # v4.1.0
        id: attest
        with:
          subject-path: "./dist/citric*"
      - name: Upload attestation bundle to release
        env:
          FILE_PATH: ${{ steps.attest.outputs.bundle-path }}
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TAG: ${{ github.event.inputs.tag || github.ref_name }}
        run: gh release upload "$TAG" "$FILE_PATH#attestations.intoto.jsonl"
