name: Coverage
on: push
jobs:
  coverage:
    runs-on: ubuntu-latest
    env:
      SETUPTOOLS_USE_DISTUTILS: stdlib
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v1
      with:
        python-version: '3.10'
        architecture: x64
    - run: pip install nox==2020.5.24
    - run: pip install poetry==1.0.5
    - run: nox --sessions tests-3.10 coverage
      env:
        CODECOV_TOKEN: ${{secrets.CODECOV_TOKEN}}
