name: Update GitHub Actions

on:
  workflow_dispatch:
  schedule:
    # Monthly
    - cron: '0 0 1 * *'

permissions: read-all

jobs:
  generate-pr:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write  # to create and update PRs
    steps:
    - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      with:
        persist-credentials: false
    - uses: actions/setup-python@0b93645e9fea7318ecaed2b359559ac225c90a2b # v5.3.0
      with:
        python-version: '3.x'
    - uses: hynek/setup-cached-uv@757bedc3f972eb7227a1aa657651f15a8527c817 # v2.3.0
    - uses: tibdex/github-app-token@3beb63f4bd073e61482598c45c71c1019b59b73a # v2.1.0
      id: generate-token
      with:
        app_id: ${{ secrets.APP_ID }}
        private_key: ${{ secrets.APP_PRIVATE_KEY }}
    - run: |
        uvx gha-update
    - uses: peter-evans/create-pull-request@5e914681df9dc83aa4e4905692ca88beb2f9e91f # v7.0.5
      with:
        token: ${{ steps.generate-token.outputs.token }}
        title: "chore: Update GitHub Actions"
        branch: chore/update-gha
        commit-message: "chore: Update GitHub Actions"
        body: |
          Update GitHub Actions to the latest versions.

          Uses https://github.com/davidism/gha-update.
        reviewers: |
          edgarrmondragon
        assignees: |
          edgarrmondragon
        delete-branch: true
        labels: Release
