name: Update LimeSurvey Docker tags

on:
  schedule:
  # Every Monday at 12:00 UTC
  - cron: "0 12 * * 1"
  workflow_dispatch: {}

jobs:
  update_tags:
    name: Update tags file and README
    runs-on: ubuntu-latest
    steps:
    - name: Check out the repository
      uses: actions/checkout@v3.6.0

    - name: Setup Python 3.11
      uses: actions/setup-python@v4.7.0
      with:
        python-version: "3.11"
        architecture: x64

    - name: Install Poetry
      env:
        PIP_CONSTRAINT: .github/workflows/constraints.txt
      run: |
        pipx install poetry --verbose
        poetry --version

    - name: Install Nox
      env:
        PIP_CONSTRAINT: .github/workflows/constraints.txt
      run: |
        pipx install nox
        pipx inject nox nox-poetry
        nox --version

    - name: Generate Integration Status Table
      id: nox-status
      env:
        NOXSESSION: generate-tags
      run: |
        nox

    - uses: tibdex/github-app-token@v1.8.0
      id: generate-token
      with:
        app_id: ${{ secrets.APP_ID }}
        private_key: ${{ secrets.APP_PRIVATE_KEY }}

    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v5.0.2
      with:
        token: ${{ steps.generate-token.outputs.token }}
        title: "test: Update LimeSurvey Docker tags"
        branch: test/update-limesurvey-docker-tags
        commit-message: "test: Update LimeSurvey Docker tags"
        body: "Update LimeSurvey tags from Docker Hub"
        reviewers: |
          edgarrmondragon
        assignees: |
          edgarrmondragon
        delete-branch: true
